#cloud-config
autoinstall:
  version: 1

  early-commands:
    - |
      MODEL="$(cat /sys/class/dmi/id/product_name)"
      MODEL="$(printf '%s' "$MODEL" \
        | tr '[:upper:]' '[:lower:]' \
        | sed 's/[^a-z0-9-]/-/g' \
        | sed 's/--*/-/g' \
        | sed 's/^-//;s/-$//')"

      sed -i "s/__HOSTNAME__/${MODEL}/" /autoinstall.yaml

  identity:
    hostname: __HOSTNAME__
    username: harmony
    password: "$6$B.g4ap4wcNilEUYs$D8h5ybJs7ASSg8Sh9bjkkGitSlEPlwMYaEDB9tMDsoSsgTTqzBlxCNI0eWQN84ssHUA0f.NHFOdEf1ETQ2euy/"

  locale: en_US.UTF-8
  keyboard:
    layout: us

  timezone: America/Indiana/Indianapolis

  storage:
    layout:
      name: direct

  updates: all